### ISSUE TITLE
Can't access jessie-updates

### ISSUE THREAD

**Issue by admbtlr** [namshi/docker-smtp#50]
A few days ago, Debian announced the removal of non-LTS Jessie from their mirrors:

https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

This causes problems when trying to use the namshi/smtp docker image:

```Step 1/2 : FROM namshi/smtp
 ---> f2dffd734243
Step 2/2 : RUN apt-get update && apt-get dist-upgrade -y
 ---> Running in cff38b0d4315
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Ign http://deb.debian.org jessie-updates InRelease
Get:2 http://deb.debian.org jessie Release.gpg [2420 B]
Ign http://deb.debian.org jessie-updates Release.gpg
Get:3 http://deb.debian.org jessie Release [148 kB]
Get:4 http://security.debian.org jessie/updates/main amd64 Packages [824 kB]
Ign http://deb.debian.org jessie-updates Release
Get:5 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages
  404  Not Found
Fetched 10.1 MB in 6s (1606 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found
```

Would it be possible to switch to Stretch?

**Comment by issa-tseng** [comment]
One detail to clarify: `RUN apt-get update && apt-get dist-upgrade -y` is a step we are layering on top of the `namshi/smtp` image, so technically this is sort of our own doing.

On the other hand, the only reason we are running that step is because the version of EXIM that is presently shipping with the base `namshi/smtp` image is susceptible to that EXIM security bug that was floating around a while ago, so.. honestly, a solution to either problem would work great, and be greatly appreciated.

**Comment by odino** [comment]
@clint-tseng do you mind upgrading our base image and test it out? If it works out, you can then send a PR and we'd be happy to merge!

Cheers!

**Comment by issa-tseng** [comment]
i'll give it a shot next week!
